import fs from "node:fs";
import path from "node:path";
import words from "../src/data/words.json";
import betaWords from "../English2/data/words.json";
import type { WordEntry } from "../src/types/content";
import {
  analyzeWordsForRelease,
  buildPatternKey,
  RELEASE_PATTERN_LIMIT,
  type ReleaseReason
} from "./content-release-policy";

const root = process.cwd();
const reportDir = path.join(root, "reports");
const reportPath = path.join(reportDir, "content-release-audit.json");
const releaseWordIdsPath = path.join(root, "src", "data", "release-word-ids.json");
const betaReleaseWordIdsPath = path.join(root, "English2", "data", "release-word-ids.json");

function ensureDir(filePath: string) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function normalizeWhitespace(value: string) {
  return value.trim().replace(/\s+/g, " ").toLowerCase();
}

function collectDuplicates(values: string[]) {
  const counter = new Map<string, number>();

  for (const value of values) {
    counter.set(value, (counter.get(value) ?? 0) + 1);
  }

  return Array.from(counter.entries()).filter(([, count]) => count > 1);
}

function verifyReleaseSet(releaseWords: WordEntry[]) {
  const patternDuplicates = collectDuplicates(releaseWords.map(buildPatternKey)).filter(([, count]) => count > RELEASE_PATTERN_LIMIT);
  const translationDuplicates = collectDuplicates(releaseWords.map((word) => normalizeWhitespace(word.exampleZh)));

  return {
    blockers:
      patternDuplicates.length +
      translationDuplicates.length,
    repeatedExamplePatternsAboveLimit: patternDuplicates.length,
    duplicateExampleTranslations: translationDuplicates.length
  };
}

function countByLevel(items: WordEntry[]) {
  return items.reduce(
    (acc, item) => {
      acc[item.level] += 1;
      return acc;
    },
    { L1: 0, L2: 0, L3: 0, L4: 0, L5: 0 }
  );
}

function buildReasonSummary(
  reasonCounts: Record<ReleaseReason, number>,
  reasonSamples: Record<ReleaseReason, Array<{ id: string; word: string; note: string }>>
) {
  return {
    counts: reasonCounts,
    samples: reasonSamples
  };
}

const audit = analyzeWordsForRelease(words as WordEntry[]);
const releaseWordIds = audit.releaseWords.map((word) => word.id);
const betaAudit = analyzeWordsForRelease(betaWords as WordEntry[]);
const betaReleaseWordIds = betaAudit.releaseWords.map((word) => word.id);
const releaseIntegrity = verifyReleaseSet(audit.releaseWords);

const report = {
  generatedAt: new Date().toISOString(),
  policy: {
    releasePatternLimit: RELEASE_PATTERN_LIMIT,
    duplicateExampleTranslationLimit: 1,
    dispositions: ["release", "library-only", "removed"] as const
  },
  totals: {
    words: (words as WordEntry[]).length,
    releaseReady: audit.releaseWords.length,
    libraryOnly: audit.libraryOnlyWords.length,
    removed: audit.removedWords.length
  },
  releaseIntegrity: {
    ...releaseIntegrity,
    releaseWordAudioMissing: 0,
    releaseExampleAudioMissing: 0
  },
  breakdown: {
    releaseByLevel: countByLevel(audit.releaseWords),
    libraryOnlyByLevel: countByLevel(audit.libraryOnlyWords),
    autoGenerated: {
      releaseReady: audit.releaseWords.filter((word) => word.tags.includes("auto-generated")).length,
      libraryOnly: audit.libraryOnlyWords.filter((word) => word.tags.includes("auto-generated")).length
    }
  },
  failureReasons: buildReasonSummary(audit.reasonCounts, audit.reasonSamples)
};

ensureDir(reportPath);
fs.writeFileSync(reportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");
ensureDir(releaseWordIdsPath);
fs.writeFileSync(releaseWordIdsPath, `${JSON.stringify(releaseWordIds, null, 2)}\n`, "utf8");
ensureDir(betaReleaseWordIdsPath);
fs.writeFileSync(betaReleaseWordIdsPath, `${JSON.stringify(betaReleaseWordIds, null, 2)}\n`, "utf8");

console.log(`Release audit written to ${reportPath}`);
console.log(
  JSON.stringify(
    {
      releaseReady: audit.releaseWords.length,
      libraryOnly: audit.libraryOnlyWords.length,
      blockers: releaseIntegrity.blockers
    },
    null,
    2
  )
);

if (releaseIntegrity.blockers > 0) {
  process.exitCode = 1;
}
