import fs from "node:fs";
import path from "node:path";
import type { WordEntry } from "../src/types/content";
import contentHygiene from "./content-hygiene";

export const RELEASE_PATTERN_LIMIT = 12;
export const RELEASE_TRANSLATION_LIMIT = 1;

export type ReleaseReason =
  | "blocked-risk-term"
  | "low-quality-meaning"
  | "mojibake-or-artifact"
  | "obvious-pos-mismatch"
  | "missing-focus"
  | "focus-not-in-translation"
  | "example-missing-target"
  | "missing-word-audio"
  | "missing-example-audio"
  | "repeated-example-pattern"
  | "duplicate-example-translation";

export interface ReleaseAuditWord {
  id: string;
  word: string;
  level: WordEntry["level"];
  action: "release" | "library-only" | "removed";
  reasons: ReleaseReason[];
  examplePattern: string;
  normalizedExampleZh: string;
  difficulty: number;
  autoGenerated: boolean;
}

export interface ReleaseAuditResult {
  releaseWords: WordEntry[];
  libraryOnlyWords: WordEntry[];
  removedWords: WordEntry[];
  auditWords: ReleaseAuditWord[];
  reasonCounts: Record<ReleaseReason, number>;
  reasonSamples: Record<ReleaseReason, Array<{ id: string; word: string; note: string }>>;
}

const {
  containsBlockedChineseFragment,
  containsBlockedEnglishWord,
  containsEscapedNewlineArtifact,
  containsLowQualityMeaningMarker,
  normalizeMeaningZh
} = contentHygiene;

const root = process.cwd();

const releaseRiskTerms = [
  "boobs",
  "gay",
  "sexo",
  "sexually",
  "tranny",
  "topless",
  "xanax",
  "levitra",
  "zoophilia"
] as const;

const releaseRiskPattern = new RegExp(`\\b(?:${releaseRiskTerms.join("|")})\\b`, "i");

const pronounLikeWords = new Set([
  "i",
  "me",
  "you",
  "he",
  "him",
  "she",
  "her",
  "it",
  "we",
  "us",
  "they",
  "them",
  "my",
  "your",
  "his",
  "its",
  "our",
  "their",
  "mine",
  "yours",
  "hers",
  "ours",
  "theirs",
  "this",
  "that",
  "these",
  "those",
  "which",
  "who",
  "whom",
  "what",
  "whose",
  "someone",
  "anyone",
  "everyone",
  "something",
  "anything",
  "nothing",
  "another",
  "others",
  "either",
  "neither",
  "each"
]);

const articleLikeWords = new Set(["a", "an", "the"]);
const modalLikeWords = new Set(["can", "could", "may", "might", "must", "shall", "should", "will", "would"]);
const prepositionLikeWords = new Set([
  "about",
  "across",
  "after",
  "against",
  "among",
  "around",
  "at",
  "before",
  "beside",
  "besides",
  "between",
  "by",
  "during",
  "for",
  "from",
  "in",
  "inside",
  "into",
  "near",
  "of",
  "on",
  "onto",
  "outside",
  "over",
  "through",
  "to",
  "toward",
  "towards",
  "under",
  "upon",
  "with",
  "within",
  "without"
]);

const conjunctionLikeWords = new Set([
  "although",
  "and",
  "because",
  "but",
  "if",
  "nor",
  "or",
  "since",
  "so",
  "though",
  "unless",
  "whether",
  "while",
  "yet"
]);

function fileExists(audioPath?: string) {
  if (!audioPath?.trim() || audioPath.startsWith("speech:")) {
    return false;
  }

  const normalized = audioPath.startsWith("/") ? audioPath.slice(1) : audioPath;
  return fs.existsSync(path.join(root, "public", normalized));
}

function normalizeWhitespace(value: string) {
  return value.trim().replace(/\s+/g, " ").toLowerCase();
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function buildPatternKey(word: WordEntry) {
  return normalizeWhitespace(word.exampleEn).replace(
    new RegExp(`\\b${escapeRegExp(word.word)}\\b`, "gi"),
    "__target__"
  );
}

function normalizeExampleTranslation(word: WordEntry) {
  return normalizeWhitespace(word.exampleZh);
}

function containsMojibakeOrArtifact(value: string) {
  return containsEscapedNewlineArtifact(value) || value.includes("\uFFFD");
}

function hasReleaseRiskTerm(word: WordEntry) {
  const joined = [word.word, word.meaningZh, word.exampleEn, word.exampleZh].join(" ");
  return (
    containsBlockedEnglishWord(joined) ||
    containsBlockedChineseFragment(joined) ||
    releaseRiskPattern.test(joined)
  );
}

function buildTargetVariants(value: string) {
  const lower = value.trim().toLowerCase();
  const variants = new Set([lower]);

  variants.add(`${lower}s`);
  variants.add(`${lower}es`);
  variants.add(`${lower}ed`);
  variants.add(`${lower}d`);
  variants.add(`${lower}ing`);

  if (lower.endsWith("e") && lower.length > 2) {
    variants.add(`${lower.slice(0, -1)}ing`);
  }

  if (lower.endsWith("y") && lower.length > 2) {
    variants.add(`${lower.slice(0, -1)}ies`);
    variants.add(`${lower.slice(0, -1)}ied`);
  }

  return Array.from(variants);
}

function hasExampleTarget(word: WordEntry) {
  return buildTargetVariants(word.word).some((variant) =>
    new RegExp(`\\b${escapeRegExp(variant)}\\b`, "i").test(word.exampleEn)
  );
}

function hasObviousPartOfSpeechMismatch(word: WordEntry) {
  const token = word.word.trim().toLowerCase();
  const partOfSpeech = word.partOfSpeech.trim().toLowerCase();

  if (pronounLikeWords.has(token)) {
    return /noun|verb|adverb/.test(partOfSpeech);
  }

  if (articleLikeWords.has(token)) {
    return /noun|verb|adjective|adverb/.test(partOfSpeech);
  }

  if (modalLikeWords.has(token)) {
    return /noun|adjective|adverb/.test(partOfSpeech);
  }

  if (prepositionLikeWords.has(token)) {
    return /noun|verb|adjective|adverb/.test(partOfSpeech);
  }

  if (conjunctionLikeWords.has(token)) {
    return /noun|verb|adjective|adverb/.test(partOfSpeech);
  }

  return false;
}

function collectBaseReasons(word: WordEntry) {
  const reasons = new Set<ReleaseReason>();
  const normalizedMeaning = normalizeMeaningZh(word.meaningZh);
  const joinedChinese = [word.meaningZh, word.exampleZh, word.exampleFocusZh ?? ""].join(" ");

  if (hasReleaseRiskTerm(word)) {
    reasons.add("blocked-risk-term");
  }

  if (!normalizedMeaning || normalizedMeaning.length < 2 || containsLowQualityMeaningMarker(word.meaningZh)) {
    reasons.add("low-quality-meaning");
  }

  if (containsMojibakeOrArtifact(joinedChinese)) {
    reasons.add("mojibake-or-artifact");
  }

  if (hasObviousPartOfSpeechMismatch(word)) {
    reasons.add("obvious-pos-mismatch");
  }

  if (!word.exampleFocusZh?.trim()) {
    reasons.add("missing-focus");
  } else if (!word.exampleZh.includes(word.exampleFocusZh)) {
    reasons.add("focus-not-in-translation");
  }

  if (!hasExampleTarget(word)) {
    reasons.add("example-missing-target");
  }

  if (!fileExists(word.audioLocal)) {
    reasons.add("missing-word-audio");
  }

  if (!fileExists(word.exampleAudioLocal)) {
    reasons.add("missing-example-audio");
  }

  return reasons;
}

function createAuditWord(word: WordEntry, reasons: Set<ReleaseReason>): ReleaseAuditWord {
  return {
    id: word.id,
    word: word.word,
    level: word.level,
    action: reasons.size > 0 ? "library-only" : "release",
    reasons: Array.from(reasons),
    examplePattern: buildPatternKey(word),
    normalizedExampleZh: normalizeExampleTranslation(word),
    difficulty: word.difficulty,
    autoGenerated: word.tags.includes("auto-generated")
  };
}

export function analyzeWordsForRelease(words: WordEntry[]): ReleaseAuditResult {
  const auditWords = words.map((word) => createAuditWord(word, collectBaseReasons(word)));
  const candidateGroupsByPattern = new Map<string, ReleaseAuditWord[]>();

  for (const entry of auditWords) {
    if (entry.reasons.length > 0) {
      continue;
    }

    const current = candidateGroupsByPattern.get(entry.examplePattern) ?? [];
    current.push(entry);
    candidateGroupsByPattern.set(entry.examplePattern, current);
  }

  for (const entries of candidateGroupsByPattern.values()) {
    const ordered = entries
      .slice()
      .sort((left, right) =>
        left.autoGenerated === right.autoGenerated
          ? left.difficulty - right.difficulty || words.findIndex((word) => word.id === left.id) - words.findIndex((word) => word.id === right.id)
          : Number(left.autoGenerated) - Number(right.autoGenerated)
      );

    ordered.slice(RELEASE_PATTERN_LIMIT).forEach((entry) => {
      if (!entry.reasons.includes("repeated-example-pattern")) {
        entry.reasons.push("repeated-example-pattern");
        entry.action = "library-only";
      }
    });
  }

  const candidateGroupsByTranslation = new Map<string, ReleaseAuditWord[]>();
  for (const entry of auditWords) {
    if (entry.reasons.length > 0) {
      continue;
    }

    const current = candidateGroupsByTranslation.get(entry.normalizedExampleZh) ?? [];
    current.push(entry);
    candidateGroupsByTranslation.set(entry.normalizedExampleZh, current);
  }

  for (const entries of candidateGroupsByTranslation.values()) {
    const ordered = entries
      .slice()
      .sort((left, right) => left.difficulty - right.difficulty || words.findIndex((word) => word.id === left.id) - words.findIndex((word) => word.id === right.id));

    ordered.slice(RELEASE_TRANSLATION_LIMIT).forEach((entry) => {
      if (!entry.reasons.includes("duplicate-example-translation")) {
        entry.reasons.push("duplicate-example-translation");
        entry.action = "library-only";
      }
    });
  }

  const releaseWordIdSet = new Set(
    auditWords.filter((entry) => entry.action === "release").map((entry) => entry.id)
  );
  const releaseWords = words.filter((word) => releaseWordIdSet.has(word.id));
  const libraryOnlyWords = words.filter((word) => !releaseWordIdSet.has(word.id));
  const removedWords: WordEntry[] = [];

  const reasonCounts: Record<ReleaseReason, number> = {
    "blocked-risk-term": 0,
    "low-quality-meaning": 0,
    "mojibake-or-artifact": 0,
    "obvious-pos-mismatch": 0,
    "missing-focus": 0,
    "focus-not-in-translation": 0,
    "example-missing-target": 0,
    "missing-word-audio": 0,
    "missing-example-audio": 0,
    "repeated-example-pattern": 0,
    "duplicate-example-translation": 0
  };

  const reasonSamples: Record<ReleaseReason, Array<{ id: string; word: string; note: string }>> = {
    "blocked-risk-term": [],
    "low-quality-meaning": [],
    "mojibake-or-artifact": [],
    "obvious-pos-mismatch": [],
    "missing-focus": [],
    "focus-not-in-translation": [],
    "example-missing-target": [],
    "missing-word-audio": [],
    "missing-example-audio": [],
    "repeated-example-pattern": [],
    "duplicate-example-translation": []
  };

  for (const entry of auditWords) {
    for (const reason of entry.reasons) {
      reasonCounts[reason] += 1;

      if (reasonSamples[reason].length < 12) {
        reasonSamples[reason].push({
          id: entry.id,
          word: entry.word,
          note:
            reason === "repeated-example-pattern"
              ? entry.examplePattern
              : reason === "duplicate-example-translation"
                ? entry.normalizedExampleZh
                : words.find((word) => word.id === entry.id)?.meaningZh ?? ""
        });
      }
    }
  }

  return {
    releaseWords,
    libraryOnlyWords,
    removedWords,
    auditWords,
    reasonCounts,
    reasonSamples
  };
}
